global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "1m"
scrape_configs:
  - job_name: receiver
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - app:8080
